### ISSUE TITLE
config php with mssql

### ISSUE THREAD

**Issue by Starbugstone** [Starbugstone/kivaou#1]
Need to configure php with mssql for connections

**Comment by Starbugstone** [comment]
[Windows-7.3.zip](https://github.com/Starbugstone/kivaou/files/3023412/Windows-7.3.zip)

Using the Microsoft drivers for PHP 7.3, need to put them into the ext folder

Also to activate the connections add this to php.ini:

```
extension=php_sqlsrv_73_ts.dll
extension=php_pdo_sqlsrv_73_ts.dll
```

**Comment by Starbugstone** [comment]
Doctrine config change

```
doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_sqlsrv'
#        server_version: '5.7'
#        charset: utf8mb4
#        default_table_options:
#            charset: utf8mb4
#            collate: utf8mb4_unicode_ci

#        url: '%env(resolve:DATABASE_URL)%'
        host: localhost
        dbname: kivaou
        user: kivaou
        password: p@ssword
```
